# Generated by Django 3.0.4 on 2021-06-09 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'Accountant'), (2, 'Admins'), (3, 'Doctor'), (4, 'Nurse'), (5, 'Stores_Admin')], null=True),
        ),
    ]
