# Generated by Django 3.0.4 on 2021-06-06 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PatientRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('reference_number', models.CharField(max_length=255)),
                ('patient_id', models.CharField(max_length=255)),
                ('sickness', models.CharField(max_length=255, verbose_name='Sickness')),
                ('conditions', models.TextField()),
                ('additions', models.TextField()),
                ('date_of_birth', models.DateField(auto_now=True)),
                ('contact_number', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('location', models.CharField(max_length=255, verbose_name='Facility Name')),
                ('residentialaddress', models.CharField(max_length=255, verbose_name='Facility Address')),
                ('nationality', models.CharField(max_length=255, verbose_name='Nationality')),
                ('city', models.CharField(max_length=255, verbose_name='City')),
                ('country', models.CharField(max_length=255, verbose_name='Country')),
            ],
        ),
    ]
