# Generated by Django 3.0.4 on 2021-06-07 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0002_auto_20210606_2145'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientrecord',
            old_name='additions',
            new_name='notes',
        ),
    ]
