# Generated by Django 3.0.4 on 2021-06-07 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0003_auto_20210607_0356'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientrecord',
            old_name='reference_number',
            new_name='patient_reference_number',
        ),
        migrations.AddField(
            model_name='patientrecord',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='Female', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patientrecord',
            name='title',
            field=models.CharField(choices=[('mr', 'Mr'), ('mrs', 'Mrs'), ('miss', 'Miss'), ('ms', 'Ms'), ('doctor', 'Doctor'), ('professor', 'Professor')], default='Mrs', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patientrecord',
            name='residentialaddress',
            field=models.CharField(max_length=255, verbose_name='Residential Address'),
        ),
    ]
