# Generated by Django 3.0.4 on 2020-03-27 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PatientRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('reference_number', models.CharField(max_length=255)),
                ('patient_id', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField(auto_now=True)),
                ('contact_number', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=255, verbose_name='Facility Name')),
                ('address', models.CharField(max_length=255, verbose_name='Facility Address')),
            ],
        ),
    ]
