# Generated by Django 3.0.4 on 2020-03-27 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databases', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientrecord',
            name='date_of_birth',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
