# Generated by Django 3.0.4 on 2020-03-27 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databases', '0002_auto_20200327_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientrecord',
            name='date_of_birth',
            field=models.DateField(auto_now=True),
        ),
    ]
